### ISSUE TITLE
"downloadServerConfig" fails due to server url no longer exists.

### ISSUE THREAD

**Issue by akoserwal** [redhataccess/accessproxy#4]
http://labs-git.usersys.redhat.com/manager/api/servers.json

**Comment by kunyan** [comment]
Hey @akoserwal 

Here is a workaround:

```shell
mkdir -p ~/.config/configstore/
vi accessproxy_1.yml
```
paste following code, then save it
```yml
servers:
  fte: access.devgssfte.devlab.phx1.redhat.com
  ci: access.devgssci.devlab.phx1.redhat.com
  qa: access.qa.redhat.com
  stage: access.stage.redhat.com
  matt: mnolting-insights-db.usersys.redhat.com
  prod: access.redhat.com
hosts:
  fte: fte.foo.redhat.com
  ci: ci.foo.redhat.com
  qa: qa.foo.redhat.com
  stage: stage.foo.redhat.com
  prod: prod.foo.redhat.com
```

It should be work
